### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Rafael173** [Terpz710/PiggyOutpost#2]
Está havendo um bug, quando eu troco as coordenadas iniciais ele simplesmente não me deixa entrar no servidor, eu sei que o erro está nessa parte da coordenada porque eu testei duas vezes de forma diferente. O plugin é bom e de início eu fui na coordenada inicial do posto avançado e é possível dominar e ganhar poder.

**Comment by Terpz710** [comment]
Olá, tentei recriar o problema, mas sem sucesso. Mudei as coordenadas originais e o mundo e ainda consegui entrar. Talvez seja devido a conexões. Sem nenhum log de erros ou maneiras claras de reproduzi-lo, não posso fazer muito. Além disso, escreva para mim em inglês, estou usando um tradutor. 

**NO I DO NOT TALK PORTUGUESE ENGLISH ONLY**

**Comment by Rafael173** [comment]
If it doesn't bother you, could you tell me how you did it? I changed the first coordinate of config.yml, this plugin is very good and I'm still testing it by restarting the server because the plugin is very.

**Comment by Terpz710** [comment]
No it doesn’t bother me, the disclaimer was for those who stumble across this. Can you possibly send me a video? There’s an issue with my server as well and I can’t join instantly I need to keep trying to connect and disconnect. Sometime even relaunching Minecraft. 

The ways I fixed it was if the screen takes too long to load I simply restart Minecraft and try again and after the 3rd attempt I can join.

**Comment by Rafael173** [comment]
https://youtu.be/jcYduovOUQA?feature=shared

That's the problem I'm having.

**Comment by Terpz710** [comment]
After you disconnect look through the console logs for any crash messages.

**Comment by Rafael173** [comment]
This is a problem because the console does not show any crash messages.

**Comment by Rafael173** [comment]
I don't know if I'm right but sometimes I think that the coordinates are not accepted, my map is too big, I use PiggyFactions to allow players to claim since it is a map of the earth.

**Comment by Rafael173** [comment]
I did a test by changing the coordinates again without reaching 1000+ and the server gave no errors.

**Comment by Terpz710** [comment]
I somewhat managed to reproduce it. It’s due to the coordinates being in an unloaded chunk. I’ll fix it soon.

**Comment by Rafael173** [comment]
I reported the problem because the plugin is great for complementing and improving PiggyFactions so it wouldn't be worth it for me to simply delete the plugin from the server. Congratulations

**Comment by Terpz710** [comment]
Can you see if this fixed the issue? @Rafael173 

Download: https://poggit.pmmp.io/r/235262/PiggyOutpost_dev-17.phar

**Comment by Rafael173** [comment]
The problem has been resolved, this is incredible because now players can claim the planet Earth map and gain power by dominating outposts. Thanks. 👏👏👏
